import 'package:flutter/material.dart';

import '../l10n/app_localizations.dart';
import '../l10n/localized_catalog.dart';

extension AppLocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}

/// UI strings use English keys; unknown upstream names retain their source text.
String tr(BuildContext context, String text) =>
    localizedText(context, text);

String translate(String language, String text) =>
    language.startsWith('zh') ? (chineseTranslations[text] ?? text) : text;

String sessionStatusLabel(String status) => switch (status) {
  'started' => 'Live',
  'completed' => 'Completed',
  'delayed' => 'Delayed',
  'cancelled' => 'Cancelled',
  'rescheduled' => 'Rescheduled',
  'scheduled' => 'Upcoming',
  _ => 'Status unknown',
};

const chineseTranslations = {
  'Language': '语言',
  'Follow system': '跟随系统',
  'Simplified Chinese': '简体中文',
  'Generic model': '通用模型',
  'Generic illustration': '通用技术示意',
  'Car archive': '车型档案',
  'Team-inspired colours only; not an official livery.': '仅预览车队风格配色，非官方完整涂装。',
  'Identity verified; generation geometry unavailable. Showing the generic illustration.':
      '车型身份已核验，专属几何尚未提供；当前仍展示通用示意。',
  'Official Car': '官方车型',
  'Unable to open the official page.': '无法打开官方页面。',
  'Unable to load the car model.': '无法加载赛车模型。',
  'Loading car model': '正在加载赛车模型',
  'Front view': '正面',
  'Side view': '侧面',
  'Top view': '俯视',
  'Rear view': '后方',
  'What is it?': '是什么',
  'What does it do?': '有什么作用',
  'Why does it matter?': '为什么重要',
  'Static draft awaiting human review. Current specification and upgrades: unavailable.':
      '说明为静态草稿，待人工审核。当前规格与升级信息：暂无。',
  'Component labels': '部件标注',
  'Wireframe': '线框模式',
  'Focus component': '聚焦部件',
  'Deconstruct': '拆解',
  'Assemble': '组装',
  'Livery': '涂装视图',
  'Technical': '技术视图',
  'Compare': '对比',
  'Previous': '之前',
  'Current': '当前',
  'Ghost Compare': '重影对比',
  'Overlay the previous geometry over the current car.': '将之前的几何半透明叠加到当前赛车。',
  'Two verified generation geometries are required.': '需要两份经过核验的代际几何模型。',
  'No sourced component differences are available.': '暂无有来源的部件差异。',
  'Heritage': '车型传承',
  'Generation Compare': '代际对比',
  'Specification Compare': '规格对比',
  'Launch specification': '发布规格',
  'Explore the car': '探索赛车',
  'Generic model — not a team specification.': '通用赛车示意，不代表具体车队规格。',
  'Interactive car model': '可交互赛车模型',
  'Drag to rotate · Pinch to zoom': '拖动旋转 · 双指缩放',
  'Car component': '赛车部件',
  'Nose': '鼻锥',
  'Engine Cover': '引擎盖',
  'Beam Wing': '梁翼',
  'Rotate left': '向左旋转',
  'Rotate right': '向右旋转',
  'Zoom in': '放大',
  'Zoom out': '缩小',
  'Reset view': '重置视角',
  'Front Suspension': '前悬架',
  'Front Tyres': '前轮',
  'Rear Suspension': '后悬架',
  'Rear Tyres': '后轮',
  'Previous season': '上一赛季',
  'Next season': '下一赛季',
  'Loading upgrades': '正在加载升级档案',
  'Unable to load upgrades. Please retry.': '无法加载升级档案，请重试。',
  'Showing saved upgrades. They may have changed.': '正在显示已保存的升级档案，内容可能已调整。',
  'No sourced upgrades are available for this season.': '本赛季暂无附有原始来源的升级档案。',
  'Team': '车队',
  'All teams': '全部车队',
  'Grand Prix': '大奖赛',
  'All races': '全部分站',
  'Upgrade timeline': '升级时间线',
  'Season Evolution': '赛季演进',
  'Upgrade': '存在升级',
  'No recorded upgrade': '无已记录升级',
  'This upgrade has no compatible 3D component mapping.': '该升级暂未映射到兼容的 3D 部件。',
  'Change': '变化',
  'Goal': '目标',
  'Expected effect': '预期效果',
  'introduced': '首次引入',
  'tested': '已测试',
  'retained': '已保留',
  'modified': '已修改',
  'removed': '已移除',
  'unknown': '未知',
  'Front Wing': '前翼',
  'Floor': '底板',
  'Rear Wing': '尾翼',
  'Sidepods': '侧箱',
  'Automatically remind me of upcoming races': '自动提醒后续正赛',
  'One hour before every published race, including the next race.':
      '默认提前 1 小时提醒下一场及已公布的后续正赛。',
  'Session settings below override this race only.':
      '下方场次设置仅覆盖本站；取消本站提醒不会关闭其他比赛。',
  'Automatic race reminders: 1 hour before each race.': '自动提醒已开启：每场正赛提前 1 小时。',
  'Automatic race reminders are off.': '自动正赛提醒已关闭。',
  'Scheduled races': '已安排提醒的正赛',
  'Check permissions and sync reminders': '检查权限并同步提醒',
  'Could not refresh reminders. Existing reminders are kept.':
      '暂时无法同步提醒，已安排的提醒会保留。',
  'Some schedules could not be refreshed. Existing reminders are kept.':
      '部分赛历未能更新，已有提醒会保留。',
  'Race reminders': '赛事提醒',
  'Reminders apply to this race only.': '提醒仅适用于本站比赛，各场次可单独设置。',
  'Local reminders are available in the Android and iOS apps.':
      '系统本地提醒仅支持 Android 和 iOS 应用，网页版可预览设置。',
  'Refresh the schedule before creating a reminder.': '赛历可能已过期，请刷新后再设置提醒。',
  'Session': '比赛场次',
  'Remind me': '提前提醒',
  '24 hours before': '提前 24 小时',
  '1 hour before': '提前 1 小时',
  '15 minutes before': '提前 15 分钟',
  'Custom': '自定义',
  'Minutes before start': '提前分钟数',
  'minutes before start': '分钟前提醒',
  'Starts in': '距离开始还有',
  'minutes': '分钟',
  'Saved reminder': '已保存提醒',
  'Schedule changed. Save again to update your reminder.':
      '开赛时间已变更，请重新保存以更新提醒。',
  'Choose 1 to 10080 minutes.': '请输入 1～10080 的整数分钟数（最多提前 7 天）。',
  'This reminder time has already passed.': '该提醒时间已过，请选择更短的提前时间。',
  'Unable to initialize notifications.': '无法初始化系统通知，请稍后重试。',
  'Allow notifications in system settings, then retry.': '请在系统设置中允许通知，然后重试。',
  'Allow alarms and reminders in system settings, then retry.':
      '请在系统设置中允许闹钟和提醒权限，然后重试。',
  'Unable to save reminder. Please retry.': '无法保存提醒，请重试。',
  'Reminder scheduled.': '已安排系统提醒。',
  'Reminder cancelled.': '已取消提醒。',
  'Save reminder': '保存提醒',
  'Cancel reminder': '取消提醒',
  'Saving…': '正在处理…',
  'Close': '关闭',
  'Race details': '赛事详情',
  'Race result': '正赛成绩',
  'Race story': '比赛述事',
  'Strategy view': '策略视图',
  'Tyre compounds and verified pit laps.': '轮胎配方与已验证的进站圈。',
  'Loading strategy': '正在加载策略数据',
  'Unable to load strategy. Please try again.': '无法加载策略数据，请重试。',
  'Showing saved strategy. It may have changed.': '正在显示已保存的策略数据，内容可能已调整。',
  'Strategy data is not available yet.': '暂无可验证的策略数据。',
  'Source: FastF1': '数据来源：FastF1',
  'Championship impact': '积分榜影响',
  'Standings after this race, compared with the previous round.':
      '本站赛后积分榜，与上一站对比。',
  'Loading championship impact': '正在加载积分榜影响',
  'Unable to load championship impact. Please try again.': '无法加载积分榜影响，请重试。',
  'Showing saved championship impact. It may have changed.':
      '正在显示已保存的积分榜影响，内容可能已调整。',
  'Championship data is not available yet.': '暂无可验证的积分榜数据。',
  'Drivers’ championship': '车手积分榜',
  'Constructors’ championship': '车队积分榜',
  'points': '分',
  'Stops': '进站次数',
  'Pit': '进站',
  'Tyre age': '轮胎使用圈数',
  'Soft': '软胎',
  'Medium': '中性胎',
  'Hard': '硬胎',
  'Intermediate': '半雨胎',
  'Wet': '全雨胎',
  'stop': '次进站',
  'stops': '次进站',
  'Key race facts': '关键比赛事实',
  'Loading race story': '正在加载比赛述事',
  'Unable to load race story. Please try again.': '无法加载比赛述事，请重试。',
  'Showing saved race story. It may have changed.': '正在显示已保存的比赛述事，内容可能已调整。',
  'Race story is not available yet.': '暂无可验证的比赛述事。',
  'Biggest gain': '最大进位',
  'Biggest loss': '最大退位',
  'Start': '起步',
  'Finish': '完赛',
  'View results': '查看成绩',
  'View details': '查看详情',
  'Winner': '冠军',
  'Loading results': '正在加载成绩',
  'Unable to load results. Please try again.': '无法加载成绩，请重试。',
  'Showing saved results. They may have changed.': '正在显示已保存的成绩，结果可能已调整。',
  'Results have not been published or are unavailable for this session.':
      '该场次成绩尚未公布，或暂无历史记录。',
  'Fastest lap': '最快圈',
  'Lap': '圈数',
  'Not available': '暂无数据',
  'Unknown team': '车队信息未知',
  'Time / Gap': '用时 / 差距',
  'Grid': '发车位',
  'Points': '积分',
  'Status': '完赛状态',
  'Pit lane / unlisted': '维修区发车 / 未列出',
  'Finished': '完赛',
  'Disqualified': '取消资格',
  'Retired': '退赛',
  'Accident': '事故',
  'Collision': '碰撞',
  'Engine': '引擎故障',
  'Gearbox': '变速箱故障',
  'Did not start': '未发车',
  'Home': '首页',
  'Races': '赛事',
  'Briefing': '赛后简报',
  'Verified driver and team insights, with original sources.':
      '基于原始来源核验的车手与车队洞察。',
  'Loading race briefing': '正在加载赛后简报',
  'Unable to load race briefing. Please try again.': '无法加载赛后简报，请重试。',
  'Showing saved briefing. It may have changed.': '正在显示已保存的赛后简报，内容可能已调整。',
  'No verified briefing is available for this race.': '本站暂无可核验的赛后简报。',
  'No completed race is available for briefing.': '暂无已结束的比赛可供查看赛后简报。',
  'Sources': '来源',
  'Technical themes': '技术主题',
  'Team performance': '车队表现',
  'Tyre issues': '轮胎问题',
  'Strategy issues': '策略问题',
  'Upgrade feedback': '升级反馈',
  'Driver concerns': '车手关注点',
  'Next-race expectations': '下一站预期',
  'Evolution': '赛车演进',
  'Season': '赛季',
  'Next Grand Prix': '下一站大奖赛',
  'Your local time': '当地时间',
  'Start time to be confirmed': '开赛时间待确认',
  'Time to be confirmed': '时间待确认',
  'Race weekend': '比赛周末',
  'Pre-race': '赛前',
  'Post-race': '赛后',
  'Current session': '当前场次',
  'Next session': '下一场次',
  'Next session starts in': '距离下一场次开始',
  'Weekend schedule': '周末赛程',
  'Weekend hub': '比赛周末',
  'Upcoming': '即将开始',
  'Live': '进行中',
  'Completed': '已结束',
  'Delayed': '已延迟',
  'Cancelled': '已取消',
  'Rescheduled': '已改期',
  'Status unknown': '状态未知',
  'circuit layout': '赛道轮廓',
  'turns': '个弯角',
  'Settings': '设置',
  'Following': '关注',
  'Following this season': '本赛季关注',
  'Showing saved follow context. It may have changed.': '正在显示已保存的关注信息，归属可能已变化。',
  'Follow driver': '关注车手',
  'Following driver': '已关注车手',
  'Follow team': '关注车队',
  'Following team': '已关注车队',
  'Unfollow': '取消关注',
  'Followed drivers': '已关注的车手',
  'Followed teams': '已关注的车队',
  'No drivers followed yet.': '还没有关注车手。',
  'No teams followed yet.': '还没有关注车队。',
  'Choose drivers and teams from race results.': '请在比赛结果中选择要关注的车手和车队。',
  'Spoiler-free mode': '无剧透模式',
  'Hide completed-session results until you reveal them.':
      '隐藏已结束场次的结果，直到你主动揭晓。',
  'Race completed': '比赛已结束',
  'Results hidden': '比赛结果已隐藏',
  'Reveal results': '揭晓结果',
  'Reveal this session': '揭晓本场',
  'Session times have not been published.': '各节比赛时间尚未公布。',
  'Source: Jolpica F1': '数据来源：Jolpica F1',
  'Race starts in': '距离正赛开始',
  'Scheduled start reached': '已到计划开赛时间',
  'Loading races': '正在加载赛事',
  'Unable to load races': '无法加载赛事',
  'Check your connection and try again.': '请检查网络连接后重试。',
  'Retry': '重试',
  'Refresh': '刷新',
  'Updated': '更新于',
  'Showing saved schedule. Times may have changed.': '正在显示已保存的赛历，比赛时间可能已调整。',
  'Showing saved race summaries. Results may have changed.':
      '正在显示已保存的比赛摘要，成绩可能已调整。',
  'No published races yet. Check back for the next schedule.':
      '暂无已公布的赛事，请稍后查看新赛历。',
  'Coming later': '即将推出',
  'Driver insights, with the original sources.': '提炼车手观点，保留原始来源。',
  'Interview summaries will arrive after the race database is ready.':
      '赛事数据库完善后，将提供车手采访摘要。',
  'Follow what changes on the cars.': '追踪赛车的每一次技术变化。',
  'Verified upgrade timelines come first. Interactive car models follow.':
      '先建立可信的升级时间线，再加入交互式赛车模型。',
  'FP1': '第一节练习赛',
  'FP2': '第二节练习赛',
  'FP3': '第三节练习赛',
  'Qualifying': '排位赛',
  'Sprint': '冲刺赛',
  'Sprint Qualifying': '冲刺排位赛',
  'Race': '正赛',
  'Australian Grand Prix': '澳大利亚大奖赛',
  'Chinese Grand Prix': '中国大奖赛',
  'Japanese Grand Prix': '日本大奖赛',
  'Bahrain Grand Prix': '巴林大奖赛',
  'Saudi Arabian Grand Prix': '沙特阿拉伯大奖赛',
  'Miami Grand Prix': '迈阿密大奖赛',
  'Canadian Grand Prix': '加拿大大奖赛',
  'Monaco Grand Prix': '摩纳哥大奖赛',
  'Spanish Grand Prix': '西班牙大奖赛',
  'Austrian Grand Prix': '奥地利大奖赛',
  'British Grand Prix': '英国大奖赛',
  'Belgian Grand Prix': '比利时大奖赛',
  'Hungarian Grand Prix': '匈牙利大奖赛',
  'Dutch Grand Prix': '荷兰大奖赛',
  'Italian Grand Prix': '意大利大奖赛',
  'Azerbaijan Grand Prix': '阿塞拜疆大奖赛',
  'Singapore Grand Prix': '新加坡大奖赛',
  'United States Grand Prix': '美国大奖赛',
  'Mexico City Grand Prix': '墨西哥城大奖赛',
  'Mexican Grand Prix': '墨西哥大奖赛',
  'São Paulo Grand Prix': '圣保罗大奖赛',
  'Brazilian Grand Prix': '巴西大奖赛',
  'Las Vegas Grand Prix': '拉斯维加斯大奖赛',
  'Qatar Grand Prix': '卡塔尔大奖赛',
  'Abu Dhabi Grand Prix': '阿布扎比大奖赛',
  'Madrid Grand Prix': '马德里大奖赛',
  'Emilia Romagna Grand Prix': '艾米利亚-罗马涅大奖赛',
  'Baku City Circuit': '巴库城市赛道',
  'Shanghai International Circuit': '上海国际赛车场',
  'Suzuka Circuit': '铃鹿赛道',
  'Marina Bay Street Circuit': '滨海湾街道赛道',
  'Circuit de Monaco': '摩纳哥赛道',
  'Silverstone Circuit': '银石赛道',
  'Albert Park Grand Prix Circuit': '阿尔伯特公园赛道',
};
